### ISSUE TITLE
Cursor is not pointing to correct position after scrolling

### ISSUE THREAD

**Issue by adsonvinicius** [michaelbrusegard/WebGL-Fluid-Enhanced#10]
Testing the sample cursor moving effect in readme, when a page scrolls the previous position saved does not consider the scroll position difference, so event.X and event.Y are not the same when moving again.

**Comment by michaelbrusegard** [comment]
@adsonvinicius sorry for the late reply, GitHub decided to not notify me ¯\_(ツ)_/¯. Anyway I am unable to replicate your issue since the preview does not have scrolling (the canvas fills the whole viewport). Did you encounter this issue somewhere else?
