### ISSUE TITLE
Make it look like water

### ISSUE THREAD

**Issue by mak33v** [michaelbrusegard/WebGL-Fluid-Enhanced#9]
Hello. I'm trying unsuccessfully to make it look like water, maybe someone has some experience in this direction. Thanks a lot for any help.

**Comment by michaelbrusegard** [comment]
So you can't make it look exactly like water. By messing around in the config I found some settings which I personally feel behave and feel like water, but how much is difficult to say. It will never be exactly like in real life.

Here is a screenshot:
![fluid](https://github.com/michaelbrusegard/WebGL-Fluid-Enhanced/assets/56915010/d6bb170e-9229-4cf4-9464-a1e3d1eba706)

This is the config I used:
```js
const config = {
  DENSITY_DISSIPATION: 0.5,
  VELOCITY_DISSIPATION: 0,
  PRESSURE: 0.7,
  CURL: 5,
  COLOR_PALETTE: ["#00FFFF","#00DBFF","#10A5F5","#0C71E0","#0859C6"],
  BLOOM: false,
};
```

Good luck.

**Comment by michaelbrusegard** [comment]
https://webgl-fluid-enhanced.michaelbrusegard.com/docs/examples/water
